domain_path: C:\work\github\gonghack-PS\gonghack_pl\export\gonghack_pl\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
